### PR TITLE
Remove license phpdoc annotation

### PR DESCRIPTION
**Pull request by chalasr**
For consistency with other PSRs. Not doing the inverse because it doesn't seem useful to me.

### CODE REVIEW

**Review by mnapoli — APPROVED** [review]
👍  but for such a change maybe @michaelcullum or someone else needs to validate this?

**Review by nunomaduro — APPROVED** [review]

**Review by Jean85 — APPROVED** [review]
I agree with this change, but I don't think it warrants a new tag.

**Comment by chalasr** [comment]
Can we merge or close here? Please advise.

**Comment by michaelcullum** [comment]
Up to the @php-fig/secretaries

**Review by michaelcullum — APPROVED** [review]

**Pull request merged**
