### PR TITLE
Moving copyright from container-interop to PHP-FIG

### PR DESCRIPTION
**Pull request by moufmouf**
... and updating the copyright year.

### CODE REVIEW

**Comment by mnapoli** [comment]
I thought about that but I'm not sure if we are allowed to change a copyright like that :/

Not that I mind at all, I think there is virtually no difference.

**Comment by michaelcullum** [comment]
Urg crap. We do need to change the copyright over but you need to get permission from everyone who has contributed to container-interop.

**Comment by mnapoli** [comment]
@michaelcullum do we really need to change the copyright? It's the MIT license so I don't see any restriction applying to anyone, but of course IANAL.

**Comment by michaelcullum** [comment]
Unfortunately yes. It could cause complications in the future otherwise.

**Comment by moufmouf** [comment]
Mmmm.... ok. So this boils down to knowing _who_ are the contributors and asking them the permission.

We have [a list of contributors in the main document](https://github.com/container-interop/container-interop/blob/master/docs/ContainerInterface-meta.md#contributors). It's mainly the people who contributed significantly to discussions or contributed to the vote about the naming of the interface.

@michaelcullum : do you think this list is enough or must we be wider and maybe add anyone making a PR ?(we received some PRs about typos and I'm not sure the authors of the PRs are in the list of contributors)

**Comment by moufmouf** [comment]
Another solution: we could add the PHP-FIG group to the list of copyright holders, as explained here: http://programmers.stackexchange.com/questions/157968/how-to-manage-a-copyright-notice-in-an-open-source-project

We would have somthing like this:

```
Original work Copyright (c) 2013 container-interop  
Modified work Copyright (c) 2016 PHP Framework Interoperability Group
```

Yet another solution: since the copyright is attributed to "container-interop" and that the "container-interop" members on Github are 4 people (me, @mnapoli , @Ocramius and @jeremeamia ), we could argue that we only need the authorization of those 4 people (which would certainly make things simpler).

And of course.... IANAL :disappointed:

**Comment by Ocramius** [comment]
Or, you can simply mention the original project in the actual specification. That is sufficient.

Either way, I'm fine with the change, please don't send me a legal form that needs signing :-P

**Comment by michaelcullum** [comment]
I don't think forms are necessary. The best person to ask about this would probably be @beberlei as I guess he handled the doctrine copyright conversion unless @Ocramius you were involved enough in that. It would be much easier to just require a :+1: from the members of @container-interop or add a second line.

**Comment by mnapoli** [comment]
I'm not against this, I just want to understand why it is necessary?

**Comment by Ocramius** [comment]
@mnapoli licence changes require pinging every contributor of currently existing code (`git blame` over current codebase). We had to do it with Doctrine ORM when moving from 2.1 to 2.2. @beberlei wrote a tool to collect feedback (that was sufficient).

I'm not entirely sure about the reasoning behind it, but I remember that we had asked the http://www.fsf.org/ for the procedure.

Any code for which we didn't get approval and that wasn't "non-minimal" required full rewrite. Luckily, nobody made a fuss about it.

**Comment by mnapoli** [comment]
:+1: but why would we want to change the license/copyright owners?

**Comment by michaelcullum** [comment]
Essentially because otherwise the FIG doesn't control essentially over its own standards copyright. Which also breaks bylaws as well as just sounding like a really bad idea.

**Comment by mnapoli** [comment]
I don't get it, it's one of the most permissive license. Anyway if you guys/gals want to work on that feel free, I'll be elsewhere unless we find a problem here.

**Comment by michaelcullum** [comment]
For the purposes of this, I think it will be sufficient to just have +1s here from contributors of >2 lines. (If there is further discussion, please could it be on the ML)

@mnapoli @moufmouf @shochdoerfer @jeremeamia @mindplay-dk @pyrsmk @njasm @BafS  @Sam-Burns @michaelcullum
Please could you post `:+1: I'm okay with the license change of the container interface to the PHP FIG` in this PR.

**Comment by BafS** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG

**Comment by jeremeamia** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG

**Comment by shochdoerfer** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG in this PR.

**Comment by mnapoli** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG

**Comment by moufmouf** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG

**Comment by njasm** [comment]
:+1: I'm okay with the license change of the container interface to the PHP FIG

**Comment by ciaranmcnulty** [comment]
This is completely unnecessary surely - it's an MIT licence, FIG would only need to own the copyright if FIG wanted to change the licence, which would be a strange move.

**Comment by mnapoli** [comment]
@ciaranmcnulty agreed, I don't see a scenario where the MIT license causes an issue.

**Comment by michaelcullum** [comment]
@ciaranmcnulty It's entirely not my decision https://github.com/php-fig/fig-standards/blob/master/bylaws/005-licensing-policies.md

I'm a secretary, I cannot just turn around and say ignore the bylaws. Please either open a ML discussion and get member projects to vote to change it or it's the way things have to be.

**Comment by mnapoli** [comment]
> All PHP-FIG code must be licensed under the MIT license.

It's already under that license.

**Comment by ciaranmcnulty** [comment]
@michaelcullum the link you provided doesn't contain the word 'copyright'

**Comment by moufmouf** [comment]
Closing this. It has been replaced by #5 which keep both copyright mentions and is probably the right thing to do.

**Pull request closed without merging**
